### ISSUE TITLE
Change the style of the Modal

### ISSUE THREAD

**Issue by echavezNS** [jorgechavz/pure-css-modal#11]
Currently the modal looks like this:

![image](https://user-images.githubusercontent.com/17257421/46468332-f97b0680-c784-11e8-9abf-afd6ccec394e.png)

I'm sure that you can make it prettier

**Comment by shaileshshivam** [comment]
I would like to work on this.

**Comment by VirginiaBalseiro** [comment]
I'm like to give it a shot. Can I take this one or is someone already working on it?

**Comment by echavezNS** [comment]
All yours @VirginiaBalseiro

**Comment by VirginiaBalseiro** [comment]
So the demo looks perfect, but when I try to open my local copy, I get this:

![screenshot2](https://user-images.githubusercontent.com/28412960/46471527-87b8b200-c7b0-11e8-8b69-33c2f0650e19.png)

I tried setting up a test project following the installation instructions in the readme, and the same happens: 

![screenshot1](https://user-images.githubusercontent.com/28412960/46471540-9acb8200-c7b0-11e8-99b0-b4b1a0c3ff3e.png)

Any ideas? thanks!

**Comment by echavezNS** [comment]
Do you get any console error?

**Comment by VirginiaBalseiro** [comment]
Failed to load resource: net::ERR_FILE_NOT_FOUND : analytics.js:1

**Comment by Quantumf0x** [comment]
> I'm like to give it a shot. Can I take this one or is someone already working on it?

I was working on it
